In [0]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import SGDClassifier



In [0]:
data=pd.read_csv("data.csv")

In [0]:
data.head(10)

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678
5    843786         M  ...          0.3985                  0.12440
6    844359         M  ...          0.3063                  0.08368
7  84458202         M  ...          0.3196                  0.11510
8    844981         M  ...          0.4378                  0.10720
9  84501001         M  ...          0.4366                  0.20750

[10 rows x 32 columns]

In [0]:
data.describe()

id  radius_mean  ...  symmetry_worst  fractal_dimension_worst
count  5.690000e+02   569.000000  ...      569.000000               569.000000
mean   3.037183e+07    14.127292  ...        0.290076                 0.083946
std    1.250206e+08     3.524049  ...        0.061867                 0.018061
min    8.670000e+03     6.981000  ...        0.156500                 0.055040
25%    8.692180e+05    11.700000  ...        0.250400                 0.071460
50%    9.060240e+05    13.370000  ...        0.282200                 0.080040
75%    8.813129e+06    15.780000  ...        0.317900                 0.092080
max    9.113205e+08    28.110000  ...        0.663800                 0.207500

[8 rows x 31 columns]

In [0]:
#Dropping the ID feature:
Data=data.drop(['id'],axis=1)
Data.shape

(569, 31)

In [0]:
laben=LabelEncoder()
DATA=Data
DATA.diagnosis=laben.fit_transform(DATA.diagnosis)
DATA

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0            1        17.99  ...          0.4601                  0.11890
1            1        20.57  ...          0.2750                  0.08902
2            1        19.69  ...          0.3613                  0.08758
3            1        11.42  ...          0.6638                  0.17300
4            1        20.29  ...          0.2364                  0.07678
..         ...          ...  ...             ...                      ...
564          1        21.56  ...          0.2060                  0.07115
565          1        20.13  ...          0.2572                  0.06637
566          1        16.60  ...          0.2218                  0.07820
567          1        20.60  ...          0.4087                  0.12400
568          0         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [0]:
corr_=DATA.corr()
corr_["diagnosis"].sort_values(ascending=False)


diagnosis                  1.000000
concave points_worst       0.793566
perimeter_worst            0.782914
concave points_mean        0.776614
radius_worst               0.776454
perimeter_mean             0.742636
area_worst                 0.733825
radius_mean                0.730029
area_mean                  0.708984
concavity_mean             0.696360
concavity_worst            0.659610
compactness_mean           0.596534
compactness_worst          0.590998
radius_se                  0.567134
perimeter_se               0.556141
area_se                    0.548236
texture_worst              0.456903
smoothness_worst           0.421465
symmetry_worst             0.416294
texture_mean               0.415185
concave points_se          0.408042
smoothness_mean            0.358560
symmetry_mean              0.330499
fractal_dimension_worst    0.323872
compactness_se             0.292999
concavity_se               0.253730
fractal_dimension_se       0.077972
symmetry_se               -0

In [0]:
#Model
X=DATA.iloc[:,1:]
y=DATA.iloc[:,0]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)
print(X_train.shape)
print(X_test.shape)

(455, 30)
(114, 30)


In [0]:
#LOGISTIC CLASSIFIER
model=LogisticRegression(random_state=2)
model.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=2, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred=model.predict(X_test)

In [0]:
#CONFUSION MATRIX
conf=confusion_matrix(y_test,y_pred)
print(conf)

[[64  5]
 [ 4 41]]


In [0]:
#ACCURACY USING LOGISTIC REGRESSION
accuracy=((65+42)/(65+4+3+42))
print(accuracy)

0.9385964912280702


In [0]:
#SGD CLASSIFIER
model2=SGDClassifier(random_state=30)
model2.fit(X_train,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=30, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
y_pred=sgd.predict(X_test)

In [0]:
conf=confusion_matrix(y_test,y_pred)
print(conf)

[[58 11]
 [ 4 41]]


In [0]:
#ACCURACY FOR SGD
accuracy=((58+41)/(58+11+4+41))
print("Accuracy for SGD is:",accuracy*100,"%")

Accuracy for SGD is: 86.8421052631579 %


In [0]:
#Accuracy using CV in Logistic classifier
from sklearn.model_selection import cross_val_score
cross_val_score(model2,X_train,y_train,cv=10,scoring="accuracy")

array([0.91304348, 0.95652174, 0.82608696, 0.93478261, 0.89130435,
       0.86666667, 0.91111111, 0.84444444, 0.91111111, 0.97777778])

In [0]:
#SVM
from sklearn import svm
model3=svm.SVC(kernel="linear")
model3.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred=model3.predict(X_test)

In [0]:
conf=confusion_matrix(y_test,y_pred)
conf

array([[66,  3],
       [ 3, 42]])

In [0]:
print("ACCURACY:",((66+42)/(66+3+3+42))*100)

ACCURACY: 94.73684210526315


In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[66  3]
 [ 3 42]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96        69
           1       0.93      0.93      0.93        45

    accuracy                           0.95       114
   macro avg       0.94      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

